# Generated by Django 5.0.6 on 2024-06-30 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playback_type', models.CharField(choices=[('local', 'local'), ('dash', 'dash'), ('cdn1', 'cdn_dash'), ('cdn2', 'cdn_hls')], max_length=10)),
                ('uri', models.CharField(max_length=200)),
                ('yt_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Tom and Jerry', max_length=100)),
                ('duration', models.IntegerField(help_text='video duration in seconds')),
                ('genre', models.CharField(default='comedy', max_length=50)),
                ('year', models.IntegerField(default=2000)),
                ('image', models.CharField(max_length=200)),
                ('summary', models.CharField(default='No summary available at the moment', max_length=200)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail', to='videoPlayer.video')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(choices=[('positive', 'positive'), ('negative', 'negative'), ('neutral', 'neutral')], max_length=20)),
                ('name', models.CharField(default='John Doe', max_length=30)),
                ('text', models.CharField(default='great video!!!', max_length=300)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='videoPlayer.video')),
            ],
        ),
    ]
