# Generated by Django 5.0.6 on 2024-06-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoPlayer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='uri',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='yt_link',
            field=models.URLField(default='N/A'),
        ),
    ]
