# Generated by Django 5.0.6 on 2024-07-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoPlayer', '0002_alter_video_uri_alter_video_yt_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='sentiment',
            field=models.CharField(choices=[('positive', 'positive'), ('negative', 'negative'), ('neutral', 'neutral'), ('default', 'default')], default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='uri',
            field=models.CharField(default='N/A', max_length=200, unique=True),
        ),
    ]
